### ISSUE TITLE
Forking for educational purposes

### ISSUE THREAD

**Issue by niansa** [MrNeRF/gaussian-splatting-cuda#55]
Hi!

I am currently porting this project to HIP for compatibility across both Nvidia and AMD cards for purely educational purposes.
However, if I am understanding the license correctly, I am not allowed to create public forks no matter the intent.
I am wondering if that part of the license could/should be changed, and if not, if I can request permissions for forking myself.

Thank you!
Tuxifan

**Comment by MrNeRF** [comment]
Hey,
cool. Let me know how your project goes.  Of course you can fork and do whatever you want with. The only thing you are not allowed is to use it commercially. This is due to the INRIA license which I cannot change as this code is build upon the original implementation.

Have fun and let me know how things are going.
